### ISSUE TITLE
what is Incorrecty padding...?

### ISSUE THREAD

**Issue by dattadhonde** [guerrerocarlos/OpenERP-ledDisplay#2]
I am trying to install point of sale in my win- 7 and got the error...

File "C:\Program Files\OpenERP 6.1-20120628-233343\Server\server\openerp\addons\point_of_sale\point_of_sale.py", line 767, in _get_small_image
  File "encodings\base64_codec.pyo", line 42, in base64_decode
  File "base64.pyo", line 321, in decodestring
Error: Incorrect padding

Thanks & Regards 
Datta Dhonde

**Comment by guerrerocarlos** [comment]
Hello, it seems that it is a bug related specifically with the point_of_sale module, and the right place to ask about it is in: https://bugs.launchpad.net/openobject-addons/ or in any of the many mailing lists related specifically with those modules.

Wich Serie/Milestone of OpenERP 6.1 did you install ?

**Comment by guerrerocarlos** [comment]
This could be the solution to that "Incorrect Padding" problem:
http://stackoverflow.com/questions/2941995/python-ignore-incorrect-padding-error-when-base64-decoding

**Comment by dattadhonde** [comment]
i ddnt get... what you mean by Serie/Milestone?

**Comment by guerrerocarlos** [comment]
There are many "Branches" of OpenERP-addons:
https://code.launchpad.net/openobject-addons

Or you just downloaded from the official page?
